import React, { useState } from "react";
import { ActivityIndicator, Alert, Pressable, Text, View } from "react-native";
import {
  addDoc,
  collection,
  getDocs,
  limit,
  orderBy,
  query,
  serverTimestamp,
  where,
} from "firebase/firestore";
import { db } from "../firebase/firebase";
import { theme } from "../theme"; 

type Props = { currentUid: string };

export default function GenerateMatchButton({ currentUid }: Props) {
  const [loading, setLoading] = useState(false);

  const generateMatch = async () => {
    setLoading(true);
    try {
      // 1) Highest urgency open request
      const reqQ = query(
        collection(db, "requests"),
        where("status", "==", "open"),
        orderBy("urgency", "desc"),
        limit(1)
      );
      const reqSnap = await getDocs(reqQ);
      if (reqSnap.empty) {
        Alert.alert("No open requests found");
        return;
      }
      const reqDoc = reqSnap.docs[0];
      const req: any = reqDoc.data();

      // 2) Open offer with same category
      const offerQ = query(
        collection(db, "offers"),
        where("status", "==", "open"),
        where("category", "==", req.category),
        limit(1)
      );
      const offerSnap = await getDocs(offerQ);
      if (offerSnap.empty) {
        Alert.alert("No matching offers found", `Category: ${req.category}`);
        return;
      }
      const offerDoc = offerSnap.docs[0];
      const offer: any = offerDoc.data();

      // 3) Create match doc
      const urgency = Number(req.urgency ?? 1);
      const score = 0.7 + 0.06 * urgency;
      const reasons = [
        `Highest urgency request (${urgency}/5)`,
        `Category match: ${req.category}`,
        "Generated by MVP matcher",
      ];

      await addDoc(collection(db, "matches"), {
        offerId: offerDoc.id,
        requestId: reqDoc.id,
        offerTitle: offer.title ?? "Offer",
        requestTitle: req.title ?? "Request",
        offerOwnerUid: offer.ownerUid,
        requestOwnerUid: req.ownerUid,
        score,
        reasons,
        status: "proposed",
        createdAt: serverTimestamp(),
      });

      Alert.alert("✅ Match generated", "Check Match Inbox");
    } catch (e: any) {
      console.error(e);
      Alert.alert("Error generating match", e?.message ?? "Check console");
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={{ marginBottom: 12 }}>
      <Pressable
        onPress={generateMatch}
        disabled={loading}
        style={({ pressed }) => ({
          backgroundColor: pressed ? theme.greenDark : theme.green,
          paddingVertical: 12,
          borderRadius: 12,
          opacity: loading ? 0.7 : 1,
        })}
      >
        {loading ? (
          <View style={{ flexDirection: "row", justifyContent: "center", gap: 10 }}>
            <ActivityIndicator />
            <Text style={{ color: "white", fontWeight: "900" }}>Generating…</Text>
          </View>
        ) : (
          <Text style={{ color: "white", fontWeight: "900", textAlign: "center" }}>
            Generate Match
          </Text>
        )}
      </Pressable>
    </View>
  );
}
